### ISSUE TITLE
Dropdowns/Numeric Input Usability Improvements

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1687]
The Dropdowns widget group includes the DropDownList, the ComboBox, the MultiSelect and the Autocomplete. The widgets share a lot in common in terms of features and implementation. 

The outcome of this effort is to further facilitate several common data entry scenarios and address critical open bugs. Completing it will bring the set quite close to feature complete state.

Note: The list above is not complete nor final. As we progress, we may decide to address a certain case with either a demo, a built-in feature, or a help article.

## New Features/Improvements

- [x] [No Data template](https://github.com/telerik/kendo-ui-core/issues/1647)
- [x] [`defaultSelected` support](https://github.com/telerik/kendo-ui-core/issues/1660)
- [x] [(MultiSelect) Preventable Events](https://github.com/telerik/kendo-ui-core/issues/1658)
- [x] [(Autocomplete) Multiple separators](https://github.com/telerik/kendo-ui-core/issues/1656)
- [x] [AutoWidth configuration option](https://github.com/telerik/kendo-ui-core/issues/1654)
- [x] [“Clear” button](https://github.com/telerik/kendo-ui-core/issues/1650)
- [x] [Footer template](https://github.com/telerik/kendo-ui-core/issues/1649)
- [x] [(ComboBox) Copy maxlength attribute](https://github.com/telerik/kendo-ui-core/issues/1691)
- [x] [Enhance the search box behavior, so that no data is requested initially](https://github.com/telerik/kendo-ui-core/issues/1661)
- [x] [Virtualization support without a value mapper](https://github.com/telerik/kendo-ui-core/issues/1659)
- [x] [Add an option to Autocomplete to not show all items on length = 0](https://github.com/telerik/kendo-ui-core/issues/1653)

## Bugs

- [x] [(Numeric) Update the model when numeric value is decreased\increased by the arrows (AngularJS)](https://github.com/telerik/kendo-ui-core/issues/1657)
- [x] [IE - when the page is scrolled in Right To Left the popup window's position is wrong ](https://github.com/telerik/kendo-ui-core/issues/673)
- [x] [(ComboBox) Flash of unbound value](https://github.com/telerik/kendo-ui-core/issues/1652)
- [x] [(MultiSelect) Cannot remove a programatically set value from virtualized widget](https://github.com/telerik/kendo-ui-core/issues/1631)
- [x] [(MultiSelect) Clicking the 'X' in the tag does not remove the tag, but it duplicates it](https://github.com/telerik/kendo-ui-core/issues/1618)
- [x] [The filter text disappears after selecting an item in the MultiSelect ](https://github.com/telerik/kendo-ui-core/issues/1615)
- [x] [Preselected items in Multiselect are cleared upon filtering](https://github.com/telerik/kendo-ui-core/issues/1473)
- [x] [The dropdown popup appears in wrong position on mobile devices](https://github.com/telerik/kendo-ui-core/issues/1609)
- [x] [Rendered items does not correspond to the dataItems in virtualization mode + AngularJS](https://github.com/telerik/kendo-ui-core/issues/1556)
- [x] [VirtualList does not clear the selected value if valueMapper returns null](https://github.com/telerik/kendo-ui-core/issues/1502)
- [x] [Keyboard jiggling in Win Phone 10 (Edge) ](https://github.com/telerik/kendo-ui-core/issues/1425)
- [x] [(ComboBox) JS error when calling setDataSource with read DataSource in virtual mode ](https://github.com/telerik/kendo-ui-core/issues/1369)
- [x] [(Numeric) Widget does not update value, when k-ng-model is set as an object ](https://github.com/telerik/kendo-ui-core/issues/1358)
- [x] [Add two spaces and then click on multiselect , it will show empty list ](https://github.com/telerik/kendo-ui-core/issues/1050)
- [x] [Widget appends its popup in the wrong place when put in PanelBar ](https://github.com/telerik/kendo-ui-core/issues/985)

**Comment by ggkrustev** [comment]
@underlog, we are done with the story. I suppose that we can close it.

**Comment by underlog** [comment]
Excellent - an enormous "cleanup". The improvements will be available in the upcoming 2016 R3 release.
