### ISSUE TITLE
Upload Improvements

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1704]
In Q3, the upload widget is set to receive some API improvements that will enable the support of common use-case scenarios, the most notable one being the Drag and Drop custom drop zone / additional callbacks.

- [x] [The server success response will be exposed for further action from the developer](https://github.com/telerik/kendo-ui-core/issues/1679)
- [x] [remove](https://github.com/telerik/kendo-ui-core/issues/1685) and [clear](https://github.com/telerik/kendo-ui-core/issues/1670) API methods
- [x] [`getFiles` method](https://github.com/telerik/kendo-ui-core/issues/1677)
- [x] [Configuration option for allowed file types](https://github.com/telerik/kendo-ui-core/issues/1676)
- [x] [Drag and drop behavior improvements (to be explored further)](https://github.com/telerik/kendo-ui-core/issues/1672)
- [x] [Display remove button when removeUrl is not defined](https://github.com/telerik/kendo-ui-core/issues/1671)

**Comment by jlchereau** [comment]
Consider proper events to upload to Amazon S3 with signed urls:

1. get the file in a file input;
2. pass file data (content type, content length, ...) to a server which authorizes the request and returns a signed url;
3. use the signed url to upload to s3.

To achieve this we need to be able to change the upload url after the file input has changed and we need the adequate events.

**Comment by underlog** [comment]
This sounds like a nice feature request - we track these at our UserVoice portal. This existing one seems like a good fit for it. Of course, you may submit a new one, too. 

http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/6829538-upload-directly-to-azure-storage-like-radclouduplo

**Comment by jlchereau** [comment]
After having initiated many suggestions in the early days of Kendo UI, I have been out of votes for the past 2 years. Instead of rewarding suggestions, UserVoice limits suggestions. Thank you for your consideration anyway.

**Comment by Vasimovic** [comment]
Any chance you could include an upload() method?

Currently when the .AutoUpload() is set to false, an (Upload files) button shows up; however, I a have submit button which is placed outside of the upload control because I want to include other data and have a toolbar

Consequently I hide the button with CSS:

`.k-upload-selected { display: none; }`

since setting the `.Messages(m => m.UploadSelectedFiles("")` to a blank does not work

and then call the click event like so:

`$(".k-upload-selected").click()`


Example of the Upload files button showing up:

![2016-07-02_10-47-39](https://cloud.githubusercontent.com/assets/2503098/16541804/465c8490-4043-11e6-8ee1-c4fcc24f8a58.png)

Thank you

**Comment by tsvetomir** [comment]
Upload method added as part of #2106

**Comment by underlog** [comment]
The child issues of this epic are closed, closing this one too. Shipping in R3 2016.

**Comment by rmorrise** [comment]
Does this build resolve https://github.com/telerik/kendo-ui-core/issues/2386 ?

**Comment by Raisolution** [comment]
Hello @rmorrise,
the mentioned issue is not resolved in this build. It is included in our short term development plans for Q1 2017.

**Comment by jsed500** [comment]
Hi @Raisolution 

Is #2386 in the latest kendo UI release? v2017.3.1018?

I can't seem to find it anywhere. 

Thanks!
