### ISSUE TITLE
Components throwing "elem.getClientRects is not a function" with jQuery 3.0.0

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#1877]
- [x] Datepicker throws error, try to open it ,

It can be seen [here](http://dojo.telerik.com/@ipeshev/unOZi), I suspect that most of widgets that have such toggler (opening some kind of dropdown ) are broken

- [x] DateTimePicker throws same error, try to open it

- [x] Autocomplete throws same error , try to type in the input - same error + loading icon is persisted

- [x] Colorpicker throws same error, try to toggle "Choose custom color" dropdown

- [x] Combobox throws same error, try to open it

- [x] DropdownList is broken in same way

- [x] Editor is broken in same way, try to toggle "Format" menu ( the first one)

- [x] Multiselect as soon as it get focus it throws same error + loading icon is persisted

- [x] Timepicker is broken in same way, try to toggle it

- [x] Menu , try to hover some menu item with dropdown

- [x] Validator demos are also broken, though it might be since it is always used in combination with other components, it need to be confirmed working at least after removing other bugs

- [x] Toolbar that has some dropdowns also throws same error

- [x] Spreadsheed header dropdowns are throwing same error

- [x] Notification , try to click "As a popup at bottom-right"

- [x] Tooltip , try to hove some point on the map

- [x] Progressbar demos are also broken, since those are using combos, it need to be confirmed working after debug

**Comment by gyoshev** [comment]
The fix is pushed to the branch, and addresses all popups. I tried the demos in question, and it seems to work all right.

**Comment by ipeshev** [comment]
Currently the mentioned issues can not be observed. Some small glitches was observed but those are not related and thus new issues are created.

**Comment by codylindley** [comment]
I'm still seeing this issue from the npm install of "kendo-ui-core": "^2016.2.714". Everything starts working again when I remove the default jQuery dependency (i.e. jQuery 3) and manually install jQuery 2. e.g. https://www.dropbox.com/s/n8nh6bq8ryqt9np/elem.getClientRects.mp4?dl=0

**Comment by codylindley** [comment]
Well, my fault here. I thought this fix was in the latest sp2. Seems it is not, thus I should not expect a fix. Ok. Well I'm going to advocate we change the jQuery dependency (via npm), as it shouldn't be at three with these kind of issues.
