### ISSUE TITLE
Official support for jQuery 3.x

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#2250]
We're validating our components for operation with jQuery 3 and fixing issues as they're discovered.
Some work already has been done in as part of #1877
- [x] AutoComplete
- [x] Barcode
- [x] Button
- [x] ButtonGroup
- [x] Calendar
- [x] Charts
- [x] ColorPicker
- [x] ComboBox
- [x] DataSource
- [x] DatePicker
- [x] DateTimePicker
- [x] Diagram
- [x] Dialog
- [x] Drag-and-Drop
- [x] Drawing API
- [x] DropDownList
- [x] Editor
- [x] Effects
- [x] Excel Export
- [x] FilterMultiCheck
- [x] Gantt
- [x] Globalization
- [x] Grid
- [x] HierarchicalDataSource
- [x] LinearGauge
- [x] ListView
- [x] Map
- [x] MaskedTextBox
- [x] MediaPlayer
- [x] Menu
- [x] Mobile Application
- [x] Mobile Forms
- [x] Mobile Layout
- [x] Mobile SplitView
- [x] Mobile Touch Events
- [x] Mobile View
- [x] MultiSelect
- [x] Notification
- [x] NumericTextBox
- [x] PDF Export
- [x] PanelBar
- [x] PivotGrid
- [x] ProgressBar
- [x] QR Code
- [x] RadialGauge
- [x] Responsive Panel
- [x] Scheduler
- [x] ScrollView
- [x] Single-Page Application
- [x] Slider
- [x] Sortable
- [x] Sparklines
- [x] Splitter
- [x] Spreadsheet
- [x] Stock Charts
- [x] Switch
- [x] TabStrip
- [x] TimePicker
- [x] ToolBar
- [x] Tooltip
- [x] TreeList
- [x] TreeMap
- [x] TreeView
- [x] Upload
- [x] Validator
- [x] Window

**Comment by tsvetomir** [comment]
Moving this issue to the Q1 milestone as it'll likely require breaking changes in the components API

**Comment by vladimirivanoviliev** [comment]
Additional info regarding the `then` / `done` methods : 
 - https://jquery.com/upgrade-guide/3.0/#callback-invocation
 - http://stackoverflow.com/a/5436869/1679620

**Comment by vladimirivanoviliev** [comment]
### Upgrade guide for `then` method calls

Here is the way to migrate existing `then` method usages to be compatible with both jQuery 3 & existing versions:

**1) `then` method is called with single argument.** In this case the widget code should be untouched and only the tests should be updated. The tests can be upgraded by:

- calling the `jasmine.clock().install()` method inside the tests module `setup` function
- calling the `jasmine.clock().uninstall()` method inside the tests module `teardown` function
- calling the `jasmine.clock().tick()` method inside the failing sync tests

**Before:** 
```
test("sync calls change after destroy", function() {
    var model = dataSource.get(1),
        wasCalled = false;

    dataSource.remove(model);
    dataSource.bind("change", function() {
        wasCalled = true;
    });
    dataSource.sync();

    ok(wasCalled);
});
```

**After:** 

```
test("sync calls change after destroy", function() {
    var model = dataSource.get(1),
        wasCalled = false;

    dataSource.remove(model);
    dataSource.bind("change", function() {
        wasCalled = true;
    });
    dataSource.sync();

    jasmine.clock().tick();

    ok(wasCalled);
});
```

**2) `then` method is called with two arguments.** In this case we can replace the function call with `done` and `fail` methods to maintain compatibility. The tests will not require updates. 

**Before:** 
```
return this[method]({ id: model.id }).then(
                proxy(this._modelLoaded, this, model.id),
                proxy(this._modelError, this, model.id)
            );
```

**After:**
```
return this[method]({ id: model.id })
                .done(proxy(this._modelLoaded, this, model.id))
                .fail(proxy(this._modelError, this, model.id));
```

**Comment by tsvetomir** [comment]
No breaking changes were necessary in the end.
The fixes will be included in releases 2016.3.1116 and later.
