### ISSUE TITLE
TabStrip Improvements

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#2404]
- [x] Win Phone: Not able to scroll Tabs #1430
- [x] Allow an object with the request configuration options to be set per tab #90
- [x] TabStrip dynamically added tab with content is not hidden when other tab is selected. #1923
- [x] TabStrip gains focus on scrolling of the containing div #1636
- [x] "k-state-focused" class is set to the first tab when selecting another tab in IE11 #1040
- [x] TabStrip replaces the id attribute of its content div elements. #590
- [x] append method does not work when passing an ObservableArray #489

**Comment by vladimirivanoviliev** [comment]
Closed with: https://github.com/telerik/kendo-ui-core/pull/2484
