### ISSUE TITLE
Spreadsheet Events

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#2415]
- [x] Select event #2409
- [x] Cut, copy and paste events #2410
- [x] Row and column events #2412
- [x] Sheet events #2413
- [x] Format change event #2414

Ref: [UV Item](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/10274964-spreadsheet-additional-events)
