### ISSUE TITLE
Spreadsheet Improvements

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#2418]
Ref: UV Items [10274964](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/10274964-spreadsheet-additional-events), [127393](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/10069758-spreadsheet-custom-context-menu-on-cell), [15662652](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/15662652-spreadsheet-filtering-merged-rows), [16042318](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/16042318-spreadsheet-default-cell-format)

- [x] Spreadsheet Events #2415
- [x] Access to context menu instances #2411
- [x] Unable to leave formula editing mode #1941 
- [x] Filtering Merged Rows #2416 
- [x] Default Cell Style #2417
- [x] Import and export validation rules #2431
- [x] Selecting a row and inserting a new column to the left clears sheet #2299

**Comment by tsvetomir** [comment]
Bonus task :)
- [ ] Wrap cell text on word boundaries #2501

**Comment by vladimirivanoviliev** [comment]
The following issues are also included:
- [x] Sheetsbar render unusable remove button telerik/kendo#5080
