### ISSUE TITLE
DatePicker accessibility error

### ISSUE THREAD

**Issue by dbalinov** [telerik/kendo-ui-core#3129]
The option [weekColumnHeader](http://kendobuild-staging.openstack.progress.com/kendo-ui/api/javascript/ui/calendar#configuration-messages.weekColumnHeader) makes to the Calendar widget complient with web accessibility standards.

I should be able to set options.messages.weekColumnHeader to DatePicker, DateTimePricker widgets also.

- [ ] Add option to DatePicker widget
- [ ] Add option to DateTimePircker widget
- [ ] Update api reference and regenerate wrappers
- [ ] Make demos accessible

**Comment by MilenaCh** [comment]
weekColumnHeader does not work in mvc  wrapper
