### ISSUE TITLE
On Android the DateRangePicker change event close Calendar after selecting a Start Date

### ISSUE THREAD

**Issue by dmanova** [telerik/kendo-ui-core#5701]
### Bug report

When the **change** event is used in kendoDateRangePicker the Calendar gets closed after selecting a Start Date.

### Reproduction of the problem

https://dojo.telerik.com/equPapaJ
https://dojo.telerik.com/@bratanov/OHikoHaC

### Current behavior
The calendar in kendoDateRangePicker close after selecting Start Date.

### Expected/desired behavior
The calendar in kendoDateRangePicker stays open after selecting Start Date and close after selecting End Date.

### Environment

* **Kendo UI version:** 2020.1.406
* **jQuery version:** 1.12.4
* **Browser:** [Android Chrome Web Browser ]

**Comment by dmanova** [comment]
A number of test cases should be considered when fixing, testing, and verifying for regression. Here are the main items and their combinations should be considered:
1. OS: Android, iOS, Windows 
2. Browser: Chrome, Safari, Edge 
3. Mode: Mobile and Desktop mode (mobile devices only)
4. Orientation: Portrait and Landscape (mobile devices only)
3. Samples: Dojo samples in the issue and Demo pages for jQuery (incl. MVVM, AngularJS)
5. Interactivity: Check navigating in the calendar, entering dates in the input, preselected dates, etc.

**Comment by dmanova** [comment]
At the moment the following combinations are identified to show not proper behavior:

- [ ] Android; Chrome; Desktop mode, Landscape; Demo pages samples - calendar closes on first click.

- [ ] Android; Chrome; Desktop mode, Landscape; Mobile mode, Portrait and Landscape; Same demo pages in Dojo (without the site content) - calendar closes on first click. Only working in Chrome Desktop, Portrait mode.

**Comment by dmanova** [comment]
Test results form internal testing (initial fix) that fail:

- [ ] Android; Chrome; Desktop mode, Landscape; Demo pages and Dojo samples - calendar closes on the first click.

- [ ] Android; Chrome; Desktop mode, Portrait; Mobile mode, Portrait and Landscape; Demo pages samples - Not closing calendar after the click on the end date. 

- [ ] Android; Chrome; Desktop mode, Landscape; Mobile mode, Portrait and Landscape; MVVM, AngularJS demo pages samples - calendar closes on the first click.

- [ ] Android; Chrome; Desktop mode, Landscape; Same demo pages in Dojo (without the site content) - calendar closes on the first click.

- [ ] Android; Chrome; Mobile mode, Portrait and Landscape; Demo pages and Dojo samples - when reentering new dates in Chrome Mobile mode, closes when clicking in the up levels, e.g. select year.

P.S. iOS test results to be added later.
